// trx-app/src/ui/components/carrier-dashboard.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { StatusBadge, VerifiedBadge } from "./status-badge";
import ProofModal from "./proof-modal";

interface OrderRow {
  order_id: string;
  issuer_did: string;
  carrier_did: string | null;
  state: string;
  payload_offledger: {
    from: string;
    to: string;
    pickup_date: string;
    pickup_window: string;
    weight: number;
    reference: string;
  };
  verified_state: string;
  verified: boolean;
  verified_proof: {
    tx_id: string;
    block_id: string;
    timestamp: string;
    state: string;
    issuer_did: string;
    carrier_did: string | null;
    verified: boolean;
  };
}

export default function CarrierDashboard({ did }: { did: string }) {
  const [pending, setPending] = useState<OrderRow[]>([]);
  const [myBooked, setMyBooked] = useState<OrderRow[]>([]);
  const [myDone, setMyDone] = useState<OrderRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  const fetchOrders = useCallback(async () => {
    try {
      const res = await fetch("/api/orders", {
        headers: { "x-actor-did": did },
      });
      const data = await res.json();
      setPending(data.pending || []);
      setMyBooked(data.my_booked || []);
      setMyDone(data.my_done || []);
    } catch {
      // silently fail
    } finally {
      setLoading(false);
    }
  }, [did]);

  useEffect(() => {
    fetchOrders();
  }, [fetchOrders]);

  async function handleBook(orderId: string) {
    setActionLoading(orderId);
    try {
      const res = await fetch(`/api/orders/${orderId}/book`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-actor-did": did,
        },
      });
      if (!res.ok) {
        const data = await res.json();
        alert(data.error || "Failed to book load");
        return;
      }
      await fetchOrders();
    } catch {
      alert("Failed to book load");
    } finally {
      setActionLoading(null);
    }
  }

  async function handleDone(orderId: string) {
    setActionLoading(orderId);
    try {
      const res = await fetch(`/api/orders/${orderId}/done`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-actor-did": did,
        },
      });
      if (!res.ok) {
        const data = await res.json();
        alert(data.error || "Failed to mark as done");
        return;
      }
      await fetchOrders();
    } catch {
      alert("Failed to mark as done");
    } finally {
      setActionLoading(null);
    }
  }

  if (loading) {
    return <div className="p-8 text-center text-gray-400">Loading...</div>;
  }

  return (
    <div className="space-y-8">
      {/* Available Loads */}
      <div>
        <div className="mb-4">
          <h2 className="text-xl font-semibold text-gray-900">
            Available Loads
          </h2>
          <p className="text-sm text-gray-500 mt-1">
            Pending loads available for booking. Only verified loads can be booked.
          </p>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          {pending.length === 0 ? (
            <div className="p-8 text-center text-gray-400">
              No pending loads available.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-50 border-b border-gray-200">
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Load ID</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Shipper</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Lane</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Date</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Weight</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Verified</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {pending.map((order) => {
                    const isLocked =
                      order.carrier_did !== null && order.carrier_did !== did;
                    const canBook = order.verified && !isLocked;

                    return (
                      <tr
                        key={order.order_id}
                        className={`hover:bg-gray-50/50 ${isLocked ? "opacity-50" : ""}`}
                      >
                        <td className="px-4 py-3 font-mono text-xs text-gray-800">
                          {order.order_id}
                        </td>
                        <td className="px-4 py-3 text-xs text-gray-500 font-mono">
                          {order.issuer_did.slice(0, 20)}...
                        </td>
                        <td className="px-4 py-3 text-gray-700">
                          {order.payload_offledger.from} →{" "}
                          {order.payload_offledger.to}
                        </td>
                        <td className="px-4 py-3 text-gray-600">
                          {order.payload_offledger.pickup_date}
                        </td>
                        <td className="px-4 py-3 text-gray-600">
                          {order.payload_offledger.weight.toLocaleString()} lbs
                        </td>
                        <td className="px-4 py-3">
                          <VerifiedBadge verified={order.verified} />
                        </td>
                        <td className="px-4 py-3">
                          {isLocked ? (
                            <span className="text-xs text-gray-400 flex items-center gap-1">
                              <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 20 20">
                                <path
                                  fillRule="evenodd"
                                  d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                                  clipRule="evenodd"
                                />
                              </svg>
                              Locked
                            </span>
                          ) : (
                            <div className="relative group">
                              <button
                                onClick={() => handleBook(order.order_id)}
                                disabled={!canBook || actionLoading === order.order_id}
                                className="bg-indigo-600 text-white px-3 py-1.5 rounded-md text-xs font-medium hover:bg-indigo-700 transition-colors disabled:opacity-40 disabled:cursor-not-allowed cursor-pointer"
                              >
                                {actionLoading === order.order_id
                                  ? "Booking..."
                                  : "Book"}
                              </button>
                              {!order.verified && (
                                <div className="absolute bottom-full left-0 mb-1 px-2 py-1 bg-gray-800 text-white text-xs rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">
                                  Not verified on network
                                </div>
                              )}
                            </div>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      {/* My Booked Loads */}
      <div>
        <div className="mb-4">
          <h2 className="text-xl font-semibold text-gray-900">
            My Booked Loads
          </h2>
          <p className="text-sm text-gray-500 mt-1">
            Loads you have booked. Mark as done when delivery is complete.
          </p>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          {myBooked.length === 0 ? (
            <div className="p-8 text-center text-gray-400">
              You haven&apos;t booked any loads yet.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-50 border-b border-gray-200">
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Load ID</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Shipper</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Lane</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Date</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Status</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Verified</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Proof</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {myBooked.map((order) => {
                    const canDone =
                      order.verified &&
                      order.carrier_did === did &&
                      order.verified_state === "BOOKED";

                    return (
                      <tr key={order.order_id} className="hover:bg-gray-50/50">
                        <td className="px-4 py-3 font-mono text-xs text-gray-800">
                          {order.order_id}
                        </td>
                        <td className="px-4 py-3 text-xs text-gray-500 font-mono">
                          {order.issuer_did.slice(0, 20)}...
                        </td>
                        <td className="px-4 py-3 text-gray-700">
                          {order.payload_offledger.from} →{" "}
                          {order.payload_offledger.to}
                        </td>
                        <td className="px-4 py-3 text-gray-600">
                          {order.payload_offledger.pickup_date}
                        </td>
                        <td className="px-4 py-3">
                          <StatusBadge state={order.verified_state} />
                        </td>
                        <td className="px-4 py-3">
                          <VerifiedBadge verified={order.verified} />
                        </td>
                        <td className="px-4 py-3">
                          <ProofModal proof={order.verified_proof} />
                        </td>
                        <td className="px-4 py-3">
                          <div className="relative group">
                            <button
                              onClick={() => handleDone(order.order_id)}
                              disabled={!canDone || actionLoading === order.order_id}
                              className="bg-emerald-600 text-white px-3 py-1.5 rounded-md text-xs font-medium hover:bg-emerald-700 transition-colors disabled:opacity-40 disabled:cursor-not-allowed cursor-pointer"
                            >
                              {actionLoading === order.order_id
                                ? "Updating..."
                                : "Mark as Done"}
                            </button>
                            {!order.verified && (
                              <div className="absolute bottom-full left-0 mb-1 px-2 py-1 bg-gray-800 text-white text-xs rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">
                                Not verified on network
                              </div>
                            )}
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
      {/* Completed Loads */}
      {myDone.length > 0 && (
        <div>
          <div className="mb-4">
            <h2 className="text-xl font-semibold text-gray-900">
              Completed Loads
            </h2>
            <p className="text-sm text-gray-500 mt-1">
              Loads you have delivered successfully.
            </p>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-50 border-b border-gray-200">
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Load ID</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Shipper</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Lane</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Date</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Status</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Verified</th>
                    <th className="text-left px-4 py-3 font-medium text-gray-600">Proof</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {myDone.map((order) => (
                    <tr key={order.order_id} className="hover:bg-gray-50/50">
                      <td className="px-4 py-3 font-mono text-xs text-gray-800">
                        {order.order_id}
                      </td>
                      <td className="px-4 py-3 text-xs text-gray-500 font-mono">
                        {order.issuer_did.slice(0, 20)}...
                      </td>
                      <td className="px-4 py-3 text-gray-700">
                        {order.payload_offledger.from} →{" "}
                        {order.payload_offledger.to}
                      </td>
                      <td className="px-4 py-3 text-gray-600">
                        {order.payload_offledger.pickup_date}
                      </td>
                      <td className="px-4 py-3">
                        <StatusBadge state={order.verified_state} />
                      </td>
                      <td className="px-4 py-3">
                        <VerifiedBadge verified={order.verified} />
                      </td>
                      <td className="px-4 py-3">
                        <ProofModal proof={order.verified_proof} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// trx-app/src/modules/dashboard/CarrierDashboard.vue
﻿<template>
  <section class="space-y-5">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <h2 class="font-display text-2xl text-slate-900 dark:text-slate-50">Carrier Command Center</h2>
        <p class="text-sm text-slate-600 dark:text-slate-300">
          Loads update in real time from network events. No page refresh required.
        </p>
      </div>
      <BaseButton variant="secondary" size="sm" @click="void fetchOrders(true)">Refresh</BaseButton>
    </div>

    <div class="grid gap-3 sm:grid-cols-3">
      <AppCard class="space-y-1">
        <p class="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Available</p>
        <p class="text-2xl font-semibold text-trx-700 dark:text-trx-200">{{ pending.length }}</p>
      </AppCard>
      <AppCard class="space-y-1">
        <p class="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">My booked</p>
        <p class="text-2xl font-semibold text-sky-600 dark:text-sky-300">{{ myBooked.length }}</p>
      </AppCard>
      <AppCard class="space-y-1">
        <p class="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Completed</p>
        <p class="text-2xl font-semibold text-emerald-600 dark:text-emerald-300">{{ myDone.length }}</p>
      </AppCard>
    </div>

    <AppCard class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
      <div class="flex items-center gap-2 text-sm">
        <span class="inline-flex h-2.5 w-2.5 rounded-full" :class="liveDotClass" />
        <span class="text-slate-700 dark:text-slate-200">{{ liveStatusText }}</span>
      </div>
      <p class="text-xs text-slate-500 dark:text-slate-400">
        Last sync: {{ lastSyncAt || 'Never' }}
      </p>
    </AppCard>

    <AppCard
      v-if="!onChainReady.isReady.value"
      class="border border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-900/20"
    >
      <p class="text-sm text-amber-700 dark:text-amber-200">{{ onChainReady.readinessMessage.value }}</p>
    </AppCard>

    <div class="flex flex-wrap gap-2">
      <button
        v-for="tab in tabs"
        :key="tab.value"
        type="button"
        class="rounded-xl border px-3 py-2 text-xs font-semibold transition"
        :class="activeTab === tab.value
          ? 'border-trx-300 bg-trx-100 text-trx-800 dark:border-trx-700 dark:bg-trx-900/30 dark:text-trx-200'
          : 'border-slate-300 bg-white text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-slate-800'"
        @click="activeTab = tab.value"
      >
        {{ tab.label }}
      </button>
    </div>

    <AppCard v-if="loading">
      <p class="text-sm text-slate-500 dark:text-slate-400">Loading carrier dashboard...</p>
    </AppCard>

    <AppCard v-else-if="error">
      <p class="text-sm text-rose-600 dark:text-rose-300">{{ error }}</p>
    </AppCard>

    <div v-else>
      <div v-if="activeTab === 'available'" class="grid gap-4 lg:grid-cols-2">
        <AppCard v-for="order in pending" :key="`pending-${order.order_id}`" class="space-y-3">
          <div class="flex items-start justify-between gap-3">
            <div>
              <p class="font-mono text-xs text-slate-500 dark:text-slate-400">{{ order.order_id }}</p>
              <h3 class="mt-1 text-base font-semibold text-slate-800 dark:text-slate-50">{{ order.payload_offledger.from }} -> {{ order.payload_offledger.to }}</h3>
            </div>
            <VerifiedBadge :verified="order.verified" />
          </div>

          <div class="grid gap-2 text-sm sm:grid-cols-2">
            <p class="text-slate-600 dark:text-slate-300"><span class="font-semibold">Pickup:</span> {{ order.payload_offledger.pickup_date }}</p>
            <p class="text-slate-600 dark:text-slate-300"><span class="font-semibold">Weight:</span> {{ order.payload_offledger.weight.toLocaleString() }} lbs</p>
            <p class="break-all text-slate-600 dark:text-slate-300"><span class="font-semibold">Shipper DID:</span> {{ order.issuer_did.slice(0, 16) }}...</p>
            <p class="text-slate-600 dark:text-slate-300"><span class="font-semibold">Status:</span> {{ order.verified_state }}</p>
          </div>

          <div class="flex items-center justify-between gap-3">
            <ProofModal :proof="order.verified_proof" />
            <BaseButton
              size="sm"
              :disabled="!onChainReady.isReady.value || !canBook(order) || actionLoading === order.order_id"
              :loading="actionLoading === order.order_id"
              @click="handleBook(order.order_id)"
            >
              Book
            </BaseButton>
          </div>
        </AppCard>

        <AppCard v-if="pending.length === 0" class="lg:col-span-2">
          <p class="text-sm text-slate-500 dark:text-slate-400">No pending loads available.</p>
        </AppCard>
      </div>

      <div v-else-if="activeTab === 'booked'" class="grid gap-4 lg:grid-cols-2">
        <AppCard v-for="order in myBooked" :key="`booked-${order.order_id}`" class="space-y-3">
          <div class="flex items-start justify-between gap-3">
            <div>
              <p class="font-mono text-xs text-slate-500 dark:text-slate-400">{{ order.order_id }}</p>
              <h3 class="mt-1 text-base font-semibold text-slate-800 dark:text-slate-50">{{ order.payload_offledger.from }} -> {{ order.payload_offledger.to }}</h3>
            </div>
            <StatusBadge :state="order.verified_state" />
          </div>

          <div class="grid gap-2 text-sm sm:grid-cols-2">
            <p class="text-slate-600 dark:text-slate-300"><span class="font-semibold">Pickup:</span> {{ order.payload_offledger.pickup_date }}</p>
            <p class="text-slate-600 dark:text-slate-300"><span class="font-semibold">Reference:</span> {{ order.payload_offledger.reference || '-' }}</p>
          </div>

          <div class="flex items-center justify-between gap-3">
            <div class="flex items-center gap-2">
              <VerifiedBadge :verified="order.verified" />
              <ProofModal :proof="order.verified_proof" />
            </div>
            <BaseButton
              variant="success"
              size="sm"
              :disabled="!onChainReady.isReady.value || !canMarkDone(order) || actionLoading === order.order_id"
              :loading="actionLoading === order.order_id"
              @click="handleDone(order.order_id)"
            >
              Mark as done
            </BaseButton>
          </div>
        </AppCard>

        <AppCard v-if="myBooked.length === 0" class="lg:col-span-2">
          <p class="text-sm text-slate-500 dark:text-slate-400">You have no booked loads yet.</p>
        </AppCard>
      </div>

      <div v-else class="grid gap-4 lg:grid-cols-2">
        <AppCard v-for="order in myDone" :key="`done-${order.order_id}`" class="space-y-3">
          <div class="flex items-start justify-between gap-3">
            <div>
              <p class="font-mono text-xs text-slate-500 dark:text-slate-400">{{ order.order_id }}</p>
              <h3 class="mt-1 text-base font-semibold text-slate-800 dark:text-slate-50">{{ order.payload_offledger.from }} -> {{ order.payload_offledger.to }}</h3>
            </div>
            <StatusBadge :state="order.verified_state" />
          </div>

          <div class="flex items-center justify-between gap-3">
            <VerifiedBadge :verified="order.verified" />
            <ProofModal :proof="order.verified_proof" />
          </div>
        </AppCard>

        <AppCard v-if="myDone.length === 0" class="lg:col-span-2">
          <p class="text-sm text-slate-500 dark:text-slate-400">No completed loads yet.</p>
        </AppCard>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import type { VerifiedOrderRow } from "@/domain/types";
import { TrxApiError, bookOrder, listOrders, markOrderDone } from "@/services/trx/trxApi";
import { useLiveOrderSync } from "@/shared/composables/useLiveOrderSync";
import { useOnChainWriteReadiness } from "@/shared/composables/useOnChainWriteReadiness";
import AppCard from "@/shared/components/ui/AppCard.vue";
import BaseButton from "@/shared/components/ui/BaseButton.vue";
import StatusBadge from "@/shared/components/ui/StatusBadge.vue";
import VerifiedBadge from "@/shared/components/ui/VerifiedBadge.vue";
import ProofModal from "@/shared/components/ui/ProofModal.vue";

const props = defineProps<{ did: string }>();

const pending = ref<VerifiedOrderRow[]>([]);
const myBooked = ref<VerifiedOrderRow[]>([]);
const myDone = ref<VerifiedOrderRow[]>([]);
const loading = ref(true);
const actionLoading = ref<string | null>(null);
const error = ref("");
const lastSyncAt = ref("");
const activeTab = ref<"available" | "booked" | "done">("available");

const tabs = computed(() => [
  { value: "available" as const, label: `Available (${pending.value.length})` },
  { value: "booked" as const, label: `Booked (${myBooked.value.length})` },
  { value: "done" as const, label: `Completed (${myDone.value.length})` },
]);
const onChainReady = useOnChainWriteReadiness();

const liveSync = useLiveOrderSync(async () => {
  await fetchOrders(true);
});

const liveStatusText = computed(() => {
  if (liveSync.syncing.value) {
    return "Syncing blockchain events...";
  }

  if (liveSync.lastEvent.value) {
    return `Live network event: ${liveSync.lastEvent.value.type} (${liveSync.lastEvent.value.order_id})`;
  }

  return "Live sync active";
});

const liveDotClass = computed(() => {
  if (liveSync.syncing.value) {
    return "bg-amber-500";
  }

  if (liveSync.lastEvent.value) {
    return "bg-emerald-500";
  }

  return "bg-sky-500";
});

async function fetchOrders(silent = false): Promise<void> {
  if (!silent) {
    loading.value = true;
  }

  error.value = "";

  try {
    const response = await listOrders(props.did);
    if ("orders" in response) {
      throw new Error("Unexpected response for carrier dashboard");
    }

    pending.value = response.pending;
    myBooked.value = response.my_booked;
    myDone.value = response.my_done;
    lastSyncAt.value = new Date().toLocaleTimeString();
  } catch (loadError) {
    if (loadError instanceof TrxApiError) {
      error.value = loadError.message;
    } else if (loadError instanceof Error) {
      error.value = loadError.message;
    } else {
      error.value = "Unable to load carrier dashboard";
    }
  } finally {
    if (!silent) {
      loading.value = false;
    }
  }
}

function canBook(order: VerifiedOrderRow): boolean {
  const isLocked = order.carrier_did !== null && order.carrier_did !== props.did;
  return order.verified && !isLocked;
}

function canMarkDone(order: VerifiedOrderRow): boolean {
  return order.verified && order.carrier_did === props.did && order.verified_state === "BOOKED";
}

async function handleBook(orderId: string): Promise<void> {
  if (!onChainReady.isReady.value) {
    error.value = onChainReady.readinessMessage.value;
    return;
  }

  actionLoading.value = orderId;
  try {
    await bookOrder(orderId, props.did);
    await fetchOrders(true);
  } catch (bookError) {
    error.value = bookError instanceof Error ? bookError.message : "Booking failed";
  } finally {
    actionLoading.value = null;
  }
}

async function handleDone(orderId: string): Promise<void> {
  if (!onChainReady.isReady.value) {
    error.value = onChainReady.readinessMessage.value;
    return;
  }

  actionLoading.value = orderId;
  try {
    await markOrderDone(orderId, props.did);
    await fetchOrders(true);
  } catch (doneError) {
    error.value = doneError instanceof Error ? doneError.message : "Unable to mark load as done";
  } finally {
    actionLoading.value = null;
  }
}

onMounted(() => {
  liveSync.start();
  void fetchOrders();
});

onUnmounted(() => {
  liveSync.stop();
});
</script>
